
site_name: Notas de Aula em Programação Funcional
repo_url: https://github.com/lasarojc/fp_notes 
site_description: Notas de aula do curso de Sistemas Distribuídos da FACOM/UFU
edit_uri: ""

extra_javascript:
        - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
        - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        - javascripts/mathjaxhelper.js

extra_css:
        - css/extra.css

theme:
        name: material
        palette:
           - scheme: default
             toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
                accent: deep orange
                primary: blue grey
           - scheme: slate
             toggle:
                icon: material/toggle-switch
                name: Switch to light mode
        language: pt
        custom_dir: overrides
        features:
           - search.suggest
           - search.highlight
           - navigation.indexes
           - navigation.tracking

markdown_extensions:
        - toc:
            toc_depth: 5
        - attr_list
        - mdx_math
        - admonition
        - footnotes
        - pymdownx.arithmatex:
               generic: true
        - pymdownx.betterem:
               smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
        - pymdownx.highlight:
             linenums: true
             linenums_style: pymdownx-inline
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
              custom_fences:
                   - name: mermaid
                     class: mermaid
                     format: !!python/name:pymdownx.superfences.fence_div_format
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tabbed
        - pymdownx.tilde
        - pymdownx.keys
        - pymdownx.snippets:
            check_paths: true


copyright: "Copyright © 2021 Lásaro Camargos"

extra:
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/...
    - icon: fontawesome/brands/github
      link: https://github.com/lasarojc/ds_notes 
      name: These notes on Github
#    - icon: fontawesome/brands/slack
#      link: https://slack.knative.dev
#      name: Slack
  analytics:
    provider: google
    property: G-65TK61CS8M
  version:
    provider: mike


plugins:
        - search
#        - bibtex:
#            bib_file: "refs.bib"
#            cite_style: "pandoc"
        - drawio-exporter:
                cache_dir: 'drawio-exporter'
                drawio_executable: null
                drawio_args:
                    - --no-sandbox
                format: svg
                sources: '*.drawio'






nav:
        #- Início: index.html
        - Apresentação: preface.md
        - Introdução: 
            - intro/index.md
            - Haskell: intro/haskell.md
            - Mais Haskell: intro/more.md

        - Funções I:
            - functions/index.md
            - Se então, senão: functions/ifthenelse.md
            - Guardas!: functions/guards.md
            - Padrões: functions/pattern_matching.md
            - Definições Locais: functions/where_let_in.md

        - Tipos I: 
            - types/index.md
            - Básicos: types/basic.md
            - Funções: types/functions.md
            - Operadores: types/operators.md
            - Tuplas: types/tuples.md
            - Listas: types/lists.md

        - Desenvolvimento I:
            - development/index.md
            - Módulos: development/modules.md
            - HSpec: development/hspec.md
            - Quick, Check!: development/quickcheck.md

        - Funções II:
            - Padrões: functions2/pattern_matching.md
            - Recursão: functions2/recursion.md

        - Tipos II:
            - Novos: types2/userdefined.md
            - Listas: types2/lists_again.md
            - Tipos algébricos: types2/algebraic.md
            - Polimorfismo: types2/type_variables.md


        - Cálculo λ: lambda/lambda.md

        - Funções III:
            - Ordem superior: functions3/highorder.md
            - Que preguiça: functions3/lazy.md
            - Recursão de cauda: functions3/tail_recursion.md

        - Entrada e Saída: 
            - IO: io/io.md
            - Testes: tests/iotest.md

        - Desenvolvimento II: 
            - Uma aplicação: development/app.md
            - Projetos de exemplo: development/project.md
            - Erros comuns: development/comments.md