site_name: Programação Funcional
repo_url: https://github.com/lasarojc/fp_notes 
edit_uri: ""
nav:
        #- Início: index.html
        - Prefácio: preface.md #1 assinc
        - Introdução: intro.md #1 sinc
        
        - 1+1: haskell101.md #2 sinc
        - Primeiras funções: functions.md #2 sinc
        - Se então, senão: ifthenelse.md #2 sinc
        - Guardas!: guards.md
        - Tipos: types.md
        
        - Tuplas: tuples.md

        - Padrões: pattern_matching.md

        - Recursão: recursion.md

        - Where e Let-In: where_let_in.md
        
        - Listas: lists.md

        - Tipos algébricos: enum.md

        - Polimorfismo: polymorphism.md

        - Cálculo λ: lambda.md

        - Funções de alta ordem: highorder.md

        - Entrada e Saída: io.md

        - Que preguiça: lazy.md

        - Recursão de Cauda: tail_recursion.md

        - Quick, Check!: quickcheck.md

        - Projeto: project.md

        - Common Mistakes: comments.md

theme:
        name: material
        palette:
            scheme: default 
            accent: deep orange
            primary: blue grey
        language: pt
        custom_dir: overrides

plugins:
        - search
#        - bibtex:
#            bib_file: "refs.bib"
#            cite_style: "pandoc"
        - drawio-exporter:
                cache_dir: 'drawio-exporter'
                drawio_executable: null
                drawio_args:
                    - --no-sandbox
                format: svg
                sources: '*.drawio'

markdown_extensions:
        - toc:
            toc_depth: 5
        - attr_list
        - mdx_math
        - admonition
        - footnotes
        - pymdownx.arithmatex:
               generic: true
        - pymdownx.betterem:
               smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.keys
        - pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
        - pymdownx.highlight:
             linenums: true
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
              custom_fences:
                   - name: mermaid
                     class: mermaid
                     format: !!python/name:pymdownx.superfences.fence_div_format
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tabbed
        - pymdownx.tilde
        - pymdownx.tasklist
        - pymdownx.snippets:
            check_paths: true

extra_javascript:
        - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
        - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        - javascripts/mathjaxhelper.js

extra_css:
        - css/extra.css

google_analytics: ['G-PJX835H7DP', 'lasarojc.github.org/dsnotes']
